casa_color(britanico,roja)
toma(danes,te)
casa_posicion(noruego,primera)
fuma(aleman,prince)
izquierda_de(verde,blanca)
color_toma(verde,cafe)
mascota_fuma(pajaros,pall mall)
pocicion_toma(casa_centro,leche)
color_fuma(amarilla,dunhill)

fuma()
fuma()
tiene(sueco,perro)
tiene()
tiene()
tiene()
tiene()